# Lab | Data Aggregation and Filtering

In this challenge, we will continue to work with customer data from an insurance company. We will use the dataset called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by first performing data cleaning, formatting, and structuring.

1. Create a new DataFrame that only includes customers who:
   - have a **low total_claim_amount** (e.g., below $1,000),
   - have a response "Yes" to the last marketing campaign.

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis.csv"

df = pd.read_csv(url)

display(df.head())

print(df.columns.tolist())

print("Filas y columnas:", df.shape)

,Unnamed: 0,Customer,State,Customer Lifetime Value,Response,Coverage,Education,Effective To Date,EmploymentStatus,Gender,...,Number of Open Complaints,Number of Policies,Policy Type,Policy,Renew Offer Type,Sales Channel,Total Claim Amount,Vehicle Class,Vehicle Size,Vehicle Type
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2/18/11,Employed,M,...,0.0,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,NaN
1,1,KX64629,California,2228.525238,No,Basic,College,1/18/11,Unemployed,F,...,0.0,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,NaN
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2/10/11,Employed,M,...,0.0,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,1/17/11,Medical Leave,F,...,NaN,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,NaN

['Unnamed: 0', 'Customer', 'State', 'Customer Lifetime Value', 'Response', 'Coverage', 'Education', 'Effective To Date', 'EmploymentStatus', 'Gender', 'Income', 'Location Code', 'Marital Status', 'Monthly Premium Auto', 'Months Since Last Claim', 'Months Since Policy Inception', 'Number of Open Complaints', 'Number of Policies', 'Policy Type', 'Policy', 'Renew Offer Type', 'Sales Channel', 'Total Claim Amount', 'Vehicle Class', 'Vehicle Size', 'Vehicle Type']
Filas y columnas: (10910, 26)

In [2]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
    .str.replace(r"[^a-z0-9_]", "", regex=True)
)

print(df.columns.tolist())

print(df.dtypes)

display(df.isnull().sum())

['unnamed_0', 'customer', 'state', 'customer_lifetime_value', 'response', 'coverage', 'education', 'effective_to_date', 'employmentstatus', 'gender', 'income', 'location_code', 'marital_status', 'monthly_premium_auto', 'months_since_last_claim', 'months_since_policy_inception', 'number_of_open_complaints', 'number_of_policies', 'policy_type', 'policy', 'renew_offer_type', 'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size', 'vehicle_type']
unnamed_0                          int64
customer                             str
state                                str
customer_lifetime_value          float64
response                             str
coverage                             str
education                            str
effective_to_date                    str
employmentstatus                     str
gender                               str
income                             int64
location_code                        str
marital_status                       str
monthly_premium_auto               int64
months_since_last_claim          float64
months_since_policy_inception      int64
number_of_open_complaints        float64
number_of_policies                 int64
policy_type                          str
policy                               str
renew_offer_type                     str
sales_channel                        str
total_claim_amount               float64
vehicle_class                        str
vehicle_size                         str
vehicle_type                         str
dtype: object

unnamed_0                           0
customer                            0
state                             631
customer_lifetime_value             0
response                          631
coverage                            0
education                           0
effective_to_date                   0
employmentstatus                    0
gender                              0
income                              0
location_code                       0
marital_status                      0
monthly_premium_auto                0
months_since_last_claim           633
months_since_policy_inception       0
number_of_open_complaints         633
number_of_policies                  0
policy_type                         0
policy                              0
renew_offer_type                    0
sales_channel                       0
total_claim_amount                  0
vehicle_class                     622
vehicle_size                      622
vehicle_type                     5482
dtype: int64

In [3]:

df_filtered = df[
    (df["total_claim_amount"] < 1000) &
    (df["response"] == "Yes")
]

display(df_filtered.head())

print("Número de clientes filtrados:", len(df_filtered))

,unnamed_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

Número de clientes filtrados: 1399

2. Using the original Dataframe, analyze:
   - the average `monthly_premium` and/or customer lifetime value by `policy_type` and `gender` for customers who responded "Yes", and
   - compare these insights to `total_claim_amount` patterns, and discuss which segments appear most profitable or low-risk for the company.

In [4]:

responded_yes = df[df["response"] == "Yes"].copy()

print("Clientes que respondieron Yes:", len(responded_yes))

display(responded_yes.head())

Clientes que respondieron Yes: 1466

,unnamed_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_open_complaints,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,1/11/11,Employed,M,...,0.0,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A
8,8,FM55990,California,5989.773931,Yes,Premium,College,1/19/11,Employed,M,...,0.0,1,Personal Auto,Personal L1,Offer2,Branch,739.200000,Sports Car,Medsize,NaN
15,15,CW49887,California,4626.801093,Yes,Basic,Master,1/16/11,Employed,F,...,0.0,1,Special Auto,Special L1,Offer2,Branch,547.200000,SUV,Medsize,NaN
19,19,NJ54277,California,3746.751625,Yes,Extended,College,2/26/11,Employed,F,...,1.0,1,Personal Auto,Personal L2,Offer2,Call Center,19.575683,Two-Door Car,Large,A
27,27,MQ68407,Oregon,4376.363592,Yes,Premium,Bachelor,2/28/11,Employed,F,...,0.0,1,Personal Auto,Personal L3,Offer2,Agent,60.036683,Four-Door Car,Medsize,NaN

In [5]:

analysis_by_policy_gender = (
    responded_yes
    .groupby(["policy_type", "gender"])
    .agg(
        average_monthly_premium=("monthly_premium_auto", "mean"),
        average_customer_lifetime_value=("customer_lifetime_value", "mean"),
        average_total_claim_amount=("total_claim_amount", "mean"),
        number_of_customers=("customer", "count")
    )
    .round(2)
    .reset_index()
)

display(analysis_by_policy_gender)

,policy_type,gender,average_monthly_premium,average_customer_lifetime_value,average_total_claim_amount,number_of_customers
0,Corporate Auto,F,94.30,7712.63,433.74,169
1,Corporate Auto,M,92.19,7944.47,408.58,154
2,Personal Auto,F,99.00,8339.79,452.97,540
3,Personal Auto,M,91.09,7448.38,457.01,536
4,Special Auto,F,92.31,7691.58,453.28,35
5,Special Auto,M,86.34,8247.09,429.53,32

In [6]:

print("Segmentos ordenados por valor medio del cliente:")

display(
    analysis_by_policy_gender.sort_values(
        by="average_customer_lifetime_value",
        ascending=False
    )
)

print("Segmentos ordenados por reclamaciones medias:")

display(
    analysis_by_policy_gender.sort_values(
        by="average_total_claim_amount",
        ascending=True
    )
)

Segmentos ordenados por valor medio del cliente:

,policy_type,gender,average_monthly_premium,average_customer_lifetime_value,average_total_claim_amount,number_of_customers
2,Personal Auto,F,99.00,8339.79,452.97,540
5,Special Auto,M,86.34,8247.09,429.53,32
1,Corporate Auto,M,92.19,7944.47,408.58,154
0,Corporate Auto,F,94.30,7712.63,433.74,169
4,Special Auto,F,92.31,7691.58,453.28,35
3,Personal Auto,M,91.09,7448.38,457.01,536

Segmentos ordenados por reclamaciones medias:

,policy_type,gender,average_monthly_premium,average_customer_lifetime_value,average_total_claim_amount,number_of_customers
1,Corporate Auto,M,92.19,7944.47,408.58,154
5,Special Auto,M,86.34,8247.09,429.53,32
0,Corporate Auto,F,94.30,7712.63,433.74,169
2,Personal Auto,F,99.00,8339.79,452.97,540
4,Special Auto,F,92.31,7691.58,453.28,35
3,Personal Auto,M,91.09,7448.38,457.01,536

3. Analyze the total number of customers who have policies in each state, and then filter the results to only include states where there are more than 500 customers.

In [7]:

customers_by_state = df.groupby("state")["customer"].count()

display(customers_by_state.sort_values(ascending=False))

state
California    3552
Oregon        2909
Arizona       1937
Nevada         993
Washington     888
Name: customer, dtype: int64

In [8]:

states_over_500 = customers_by_state[
    customers_by_state > 500
]

display(states_over_500)

state
Arizona       1937
California    3552
Nevada         993
Oregon        2909
Washington     888
Name: customer, dtype: int64

4. Find the maximum, minimum, and median customer lifetime value by education level and gender. Write your conclusions.

In [9]:

clv_by_education_gender = (
    df.groupby(["education", "gender"])
    .agg(
        clv_max=("customer_lifetime_value", "max"),
        clv_min=("customer_lifetime_value", "min"),
        clv_median=("customer_lifetime_value", "median")
    )
    .round(2)
    .reset_index()
)

display(clv_by_education_gender)

              education gender   clv_max  clv_min  clv_median
0              Bachelor      F  73225.96  1904.00     5640.51
1              Bachelor      M  67907.27  1898.01     5548.03
2               College      F  61850.19  1898.68     5623.61
3               College      M  61134.68  1918.12     6005.85
4                Doctor      F  44856.11  2395.57     5332.46
5                Doctor      M  32677.34  2267.60     5577.67
6  High School or Below      F  55277.45  2144.92     6039.55
7  High School or Below      M  83325.38  1940.98     6286.73
8                Master      F  51016.07  2417.78     5729.86
9                Master      M  50568.26  2272.31     5579.10

In [10]:

display(
    clv_by_education_gender.sort_values(
        by="clv_median",
        ascending=False
    )
)

              education gender   clv_max  clv_min  clv_median
7  High School or Below      M  83325.38  1940.98     6286.73
6  High School or Below      F  55277.45  2144.92     6039.55
3               College      M  61134.68  1918.12     6005.85
8                Master      F  51016.07  2417.78     5729.86
0              Bachelor      F  73225.96  1904.00     5640.51
2               College      F  61850.19  1898.68     5623.61
9                Master      M  50568.26  2272.31     5579.10
5                Doctor      M  32677.34  2267.60     5577.67
1              Bachelor      M  67907.27  1898.01     5548.03
4                Doctor      F  44856.11  2395.57     5332.46

## Bonus

5. The marketing team wants to analyze the number of policies sold by state and month. Present the data in a table where the months are arranged as columns and the states are arranged as rows.

In [11]:

df["effective_to_date"] = pd.to_datetime(
    df["effective_to_date"],
    errors="coerce"
)

df["month"] = df["effective_to_date"].dt.month_name()

display(df[["state", "effective_to_date", "month"]].head())

/var/folders/85/jy3c88hd5s71n8s3cw2bq_900000gn/T/ipykernel_46850/340688862.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["effective_to_date"] = pd.to_datetime(

        state effective_to_date     month
0     Arizona        2011-02-18  February
1  California        2011-01-18   January
2  Washington        2011-02-10  February
3      Oregon        2011-01-11   January
4      Oregon        2011-01-17   January

In [12]:

policies_by_state_month = pd.pivot_table(
    df,
    index="state",
    columns="month",
    values="customer",
    aggfunc="count",
    fill_value=0
)

month_order = [
    "January", "February", "March", "April",
    "May", "June", "July", "August",
    "September", "October", "November", "December"
]

policies_by_state_month = policies_by_state_month.reindex(
    columns=[
        month for month in month_order
        if month in policies_by_state_month.columns
    ],
    fill_value=0
)

display(policies_by_state_month)

month       January  February
state
Arizona        1008       929
California     1918      1634
Nevada          551       442
Oregon         1565      1344
Washington      463       425

In [13]:

policies_sold_by_state_month = pd.pivot_table(
    df,
    index="state",
    columns="month",
    values="number_of_policies",
    aggfunc="sum",
    fill_value=0
)

policies_sold_by_state_month = policies_sold_by_state_month.reindex(
    columns=[
        month for month in month_order
        if month in policies_sold_by_state_month.columns
    ],
    fill_value=0
)

display(policies_sold_by_state_month)

month       January  February
state
Arizona        3052      2864
California     5673      4929
Nevada         1493      1278
Oregon         4697      3969
Washington     1358      1225

6.  Display a new DataFrame that contains the number of policies sold by month, by state, for the top 3 states with the highest number of policies sold.

*Hint:*
- *To accomplish this, you will first need to group the data by state and month, then count the number of policies sold for each group. Afterwards, you will need to sort the data by the count of policies sold in descending order.*
- *Next, you will select the top 3 states with the highest number of policies sold.*
- *Finally, you will create a new DataFrame that contains the number of policies sold by month for each of the top 3 states.*

In [14]:

policies_by_state = (
    df.groupby("state")["number_of_policies"]
    .sum()
    .sort_values(ascending=False)
)

top_3_states = policies_by_state.head(3)

display(top_3_states)

state
California    10602
Oregon         8666
Arizona        5916
Name: number_of_policies, dtype: int64

In [15]:

df_top_3 = df[df["state"].isin(top_3_states.index)].copy()

top_3_by_month = pd.pivot_table(
    df_top_3,
    index="state",
    columns="month",
    values="number_of_policies",
    aggfunc="sum",
    fill_value=0
)

top_3_by_month = top_3_by_month.reindex(
    columns=[
        month for month in month_order
        if month in top_3_by_month.columns
    ],
    fill_value=0
)

display(top_3_by_month)

month       January  February
state
Arizona        3052      2864
California     5673      4929
Oregon         4697      3969

7. The marketing team wants to analyze the effect of different marketing channels on the customer response rate.

Hint: You can use melt to unpivot the data and create a table that shows the customer response rate (those who responded "Yes") by marketing channel.

In [16]:

response_counts = pd.crosstab(
    df["sales_channel"],
    df["response"]
)

display(response_counts)

response         No  Yes
sales_channel
Agent          3148  742
Branch         2539  326
Call Center    1792  221
Web            1334  177

In [17]:

for response in ["Yes", "No"]:
    if response not in response_counts.columns:
        response_counts[response] = 0

response_counts["total_customers"] = (
    response_counts["Yes"] + response_counts["No"]
)

response_counts["response_rate_percent"] = (
    response_counts["Yes"] /
    response_counts["total_customers"] * 100
)

display(
    response_counts[
        ["Yes", "No", "total_customers", "response_rate_percent"]
    ].round(2).sort_values(
        by="response_rate_percent",
        ascending=False
    )
)

response       Yes    No  total_customers  response_rate_percent
sales_channel
Agent          742  3148             3890                  19.07
Web            177  1334             1511                  11.71
Branch         326  2539             2865                  11.38
Call Center    221  1792             2013                  10.98

In [18]:

response_counts_long = (
    response_counts[["Yes", "No"]]
    .reset_index()
    .melt(
        id_vars="sales_channel",
        var_name="response",
        value_name="customer_count"
    )
)

display(response_counts_long)

  sales_channel response  customer_count
0         Agent      Yes             742
1        Branch      Yes             326
2   Call Center      Yes             221
3           Web      Yes             177
4         Agent       No            3148
5        Branch       No            2539
6   Call Center       No            1792
7           Web       No            1334

External Resources for Data Filtering: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

In [ ]:
# your code goes here